const koleksi = [
  {
    "id": "egrang-bathok",
    "nama": "Egrang Bathok",
    "model": "assets/models/egrang-bathok.glb",
    "gambarReferensi": "assets/images/egrang-bathok.png",
    "bahan": "Tempurung kelapa dan tali",
    "bentuk": "Kompleks",
    "fungsi": "Ketangkasan",
    "cara": "Dipijak lalu digunakan untuk berjalan/menyeimbangkan badan",
    "asal": "Yogyakarta",
    "lokasi": "Museum Sonobudoyo Unit I",
    "digitalisasi": "3D Modeling (.glb)",
    "deskripsi": "Permainan tradisional menggunakan dua tempurung kelapa sebagai pijakan yang dihubungkan tali."
  },
  {
    "id": "gasingan",
    "nama": "Gasingan",
    "model": "assets/models/gasingan.glb",
    "gambarReferensi": "assets/images/gasingan.png",
    "bahan": "Bambu dan kayu",
    "bentuk": "Silinder/Bulat",
    "fungsi": "Alat putar",
    "cara": "Ditarik atau diputar menggunakan tali sehingga berputar",
    "asal": "Yogyakarta",
    "lokasi": "Museum Sonobudoyo Unit I",
    "digitalisasi": "3D Modeling (.glb)",
    "deskripsi": "Mainan putar tradisional berbahan bambu/kayu dengan mekanisme tali."
  },
  {
    "id": "kasti",
    "nama": "Kasti",
    "model": "assets/models/kasti.glb",
    "gambarReferensi": "assets/images/kasti.png",
    "bahan": "Kayu dan bola",
    "bentuk": "Silinder dan bulat",
    "fungsi": "Olahraga/permainan pukul",
    "cara": "Tongkat digunakan untuk memukul bola kasti",
    "asal": "Yogyakarta",
    "lokasi": "Museum Sonobudoyo Unit I",
    "digitalisasi": "3D Modeling (.glb)",
    "deskripsi": "Satu set permainan kasti berupa tongkat pemukul kayu dan bola."
  },
  {
    "id": "ketapel",
    "nama": "Ketapel",
    "model": "assets/models/ketapel.glb",
    "gambarReferensi": "assets/images/ketapel.png",
    "bahan": "Kayu/bambu, karet, kulit",
    "bentuk": "Bercabang",
    "fungsi": "Mainan tembak",
    "cara": "Karet ditarik lalu dilepas untuk melontarkan peluru kecil",
    "asal": "Yogyakarta",
    "lokasi": "Museum Sonobudoyo Unit I",
    "digitalisasi": "3D Modeling (.glb)",
    "deskripsi": "Ketapel tradisional dengan gagang bercabang, karet, dan bantalan pelontar."
  },
  {
    "id": "kodok-kodokan",
    "nama": "Kodok-Kodokan",
    "model": "assets/models/kodok-kodokan.glb",
    "gambarReferensi": "assets/images/kodok-kodokan.png",
    "bahan": "Kayu",
    "bentuk": "Oval/kerucut",
    "fungsi": "Alat bunyi",
    "cara": "Digerakkan atau ditekan sehingga menghasilkan bunyi seperti kodok",
    "asal": "Yogyakarta",
    "lokasi": "Museum Sonobudoyo Unit I",
    "digitalisasi": "3D Modeling (.glb)",
    "deskripsi": "Mainan bunyi berbentuk kodok-kodokan berwarna merah dan hijau."
  },
  {
    "id": "othok-othok",
    "nama": "Othok-Othok",
    "model": "assets/models/othok-othok.glb",
    "gambarReferensi": "assets/images/othok-othok.png",
    "bahan": "Kayu/logam tipis",
    "bentuk": "Kompleks",
    "fungsi": "Mainan air",
    "cara": "Diletakkan di air dan digerakkan dengan mekanisme sederhana",
    "asal": "Yogyakarta",
    "lokasi": "Museum Sonobudoyo Unit I",
    "digitalisasi": "3D Modeling (.glb)",
    "deskripsi": "Miniatur kapal tradisional otok-otok berwarna biru."
  },
  {
    "id": "paser",
    "nama": "Paser",
    "model": "assets/models/paser.glb",
    "gambarReferensi": "assets/images/paser.png",
    "bahan": "Kayu/bambu, logam, plastik/mika",
    "bentuk": "Kompleks",
    "fungsi": "Mainan lempar/bidik",
    "cara": "Dilempar atau diarahkan sebagai permainan ketangkasan",
    "asal": "Yogyakarta",
    "lokasi": "Museum Sonobudoyo Unit I",
    "digitalisasi": "3D Modeling (.glb)",
    "deskripsi": "Objek paser dengan badan bulat, jarum depan, dan ekor sirip."
  },
  {
    "id": "peluit-burung",
    "nama": "Peluit Burung",
    "model": "assets/models/peluit-burung.glb",
    "gambarReferensi": "assets/images/peluit-burung.png",
    "bahan": "Bambu/kayu",
    "bentuk": "Silinder",
    "fungsi": "Alat bunyi",
    "cara": "Ditiup melalui bagian ujung untuk menghasilkan suara",
    "asal": "Yogyakarta",
    "lokasi": "Museum Sonobudoyo Unit I",
    "digitalisasi": "3D Modeling (.glb)",
    "deskripsi": "Peluit tradisional berbahan bambu dengan lubang suara."
  },
  {
    "id": "peluit-burung-perkutut",
    "nama": "Peluit Burung Perkutut",
    "model": "assets/models/peluit-burung-perkutut.glb",
    "gambarReferensi": "assets/images/peluit-burung-perkutut.png",
    "bahan": "Bambu/kayu",
    "bentuk": "Silinder",
    "fungsi": "Alat bunyi",
    "cara": "Ditiup untuk menirukan suara burung perkutut",
    "asal": "Yogyakarta",
    "lokasi": "Museum Sonobudoyo Unit I",
    "digitalisasi": "3D Modeling (.glb)",
    "deskripsi": "Peluit burung perkutut dengan bentuk tabung bambu dan lubang nada."
  },
  {
    "id": "senapan-mainan",
    "nama": "Senapan Mainan",
    "model": "assets/models/senapan-mainan.glb",
    "gambarReferensi": "assets/images/senapan-mainan.png",
    "bahan": "Kayu",
    "bentuk": "Kompleks",
    "fungsi": "Mainan tembak",
    "cara": "Digunakan sebagai replika senapan mainan tradisional",
    "asal": "Yogyakarta",
    "lokasi": "Museum Sonobudoyo Unit I",
    "digitalisasi": "3D Modeling (.glb)",
    "deskripsi": "Senapan mainan kayu berwarna merah dengan pola hitam dan tali."
  },
  {
    "id": "seruling-bambu",
    "nama": "Seruling Bambu",
    "model": "assets/models/seruling-bambu.glb",
    "gambarReferensi": "assets/images/seruling-bambu.png",
    "bahan": "Bambu",
    "bentuk": "Silinder",
    "fungsi": "Alat bunyi",
    "cara": "Ditiup dan lubang nada ditutup/dibuka untuk menghasilkan melodi",
    "asal": "Yogyakarta",
    "lokasi": "Museum Sonobudoyo Unit I",
    "digitalisasi": "3D Modeling (.glb)",
    "deskripsi": "Seruling bambu tradisional dengan beberapa lubang nada."
  },
  {
    "id": "yoyo",
    "nama": "Yoyo",
    "model": "assets/models/yoyo.glb",
    "gambarReferensi": "assets/images/yoyo.png",
    "bahan": "Kayu dan tali",
    "bentuk": "Bulat/Oval",
    "fungsi": "Ketangkasan",
    "cara": "Tali digulung pada poros lalu yoyo dilempar dan ditarik kembali",
    "asal": "Yogyakarta",
    "lokasi": "Museum Sonobudoyo Unit I",
    "digitalisasi": "3D Modeling (.glb)",
    "deskripsi": "Yoyo kayu tradisional dengan tali dan pegangan kecil."
  }
];
